## more info https://github.com/crazy-max/ghaction-github-labeler
- # bot
  name: ":robot: bot"
  color: "69cde9"
  description: "Used by bots"
- # bug
  name: ":bug: bug"
  color: "b60205"
  description: "For known bugs"
  from_name: "bug"
- # Urgent
  name: ":triangular_flag_on_post: Blocker"
  color: "FFFFFF"
  description: "Release blocker"
- # dependencies
  name: ":game_die: dependencies"
  color: "0366d6"
  description: "Dependencies need fixed"
- # documentation
  name: ":books: documentation"
  color: "c5def5"
  description: ""
  from_name: "documentation"
- # duplicate
  name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: "Duplicate"
- # enhancement
  name: ":sparkles: enhancement"
  color: "0054ca"
  description: "Improve program"
- # feature request
  name: ":bulb: feature request"
  color: "0e8a16"
  description: "Feature Request"
- # feedback
  name: ":mega: feedback"
  color: "03a9f4"
  description: ""
  from: "question"
- # future maybe
  name: ":rocket: future maybe"
  color: "fef2c0"
  description: "Something to consider"
- # good first issue
  name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: "Should be easy"
- # help wanted
  name: ":pray: help wanted"
  color: "4caf50"
  description: "Need Help"
- # hold
  name: ":hand: hold"
  color: "24292f"
  description: "Hold for later version"
- # invalid
  name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: "Not a bug"
- # needs more info
  name: ":thinking: needs more info"
  color: "795548"
  description: "Need Info"
- # wontfix
  name: ":coffin: wontfix"
  color: "ffffff"
  description: ""
  from_name: "wontfix"
- # Blocker
  name: ":triangular_flag_on_post: Blocker"
  color: "ff0000"
  description: "Urgent bug, blocking release"
- # Website
  name: ":technologist: Website"
  color: "FFFFFF"
  description: "Our website"
- # Security
  name: ":closed_lock_with_key: Security"
  color: "CD5C5C"
  description: "Security issue"
- # RTC
  name: ":runner: RTC"
  color: "87ceeb"
  description: "Ready to commit"
- # Sync
  name: ":arrow_forward: Sync"
  color: "87ceeb"
  description: "Sync Action"
  from_name: "sync"
