group:

    # Sandbox update versions
    - files:
          - source: /core/resources/version.dat
            dest: /core/resources/version.dat
          - source: /bin/tmp/release/bearsampp.exe
            dest: /bearsampp.exe
      repos: |
          Bearsampp/Sandbox
