group:
  - files:
      - source: core/resources/version.dat
        dest: core/resources/version.dat
      - source: core/resources/quickpick-releases.json
        dest: core/resources/quickpick-releases.json
    repos:
      - Bearsampp/Sandbox
