os: windows
language: shell

env:
  global:
    - JAVA_HOME: /c/opt/jdk
    - ANT_HOME: /c/opt/ant

before_install:
  - git clone https://github.com/neard/dev ${TRAVIS_BUILD_DIR}/../dev
  - export PATH=${JAVA_HOME}/bin:${ANT_HOME}/bin:${PATH}
  - mkdir -p /c/opt

install:
  - |
    curl -LfsS -o /tmp/travis-wait-enhanced.zip "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_windows_x86_64.zip"
    7z x /tmp/travis-wait-enhanced.zip -y -o/usr/bin/ travis-wait-enhanced.exe -r
    travis-wait-enhanced --version
  - |
    curl -fsS -o openjdk.zip "https://download.oracle.com/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip"
    7z x openjdk.zip -y -o/c/opt/
    mv /c/opt/jdk-11.0.2 ${JAVA_HOME}
    java -version
    rm -f openjdk.zip
  - |
    curl -fsS -o apache-ant.zip "https://www.apache.org/dist/ant/binaries/apache-ant-1.10.7-bin.zip"
    7z x apache-ant.zip -y -o/c/opt/
    mv /c/opt/apache-ant-1.10.7 ${ANT_HOME}
    ant -version
    rm -f apache-ant.zip

script:
  - travis-wait-enhanced ant release

after_success:
  - export APP_VERSION=$(cat /c/neard-build/tmp/version.dat)
  - echo ${APP_VERSION}
  - mv /c/neard-build/releases/${APP_VERSION} ${TRAVIS_BUILD_DIR}/release
  - ls -al ${TRAVIS_BUILD_DIR}/release/

deploy:
  provider: releases
  api_key:
    secure: RlDjsck/nY7CHZsFQhveL0iPODhgOf/R8nVRyXVfzL3u7CWLcjq/F1XlzJMohqdNrXx8ScCBOiCTVjeAZ7k7ODG+flZuWE83rCNSkTy8+fDldurpxsQHUy7p31qQkR1TGMpoiXqDZAB/HogXzRpCNkthBsmQx6a3J0wncujG0nY=
  file_glob: true
  file: release/*
  skip_cleanup: true
  draft: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - travisci@neard.io
    on_success: always
    on_failure: always
