language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script: phpunit --version

notifications:
  slack:
    secure: Ex7cZIWY8RMX3vbgr4Lg4dyXBF2JjJWhaZv9QAPE0wQJ39hNDrad4owzQFP3HpehlMMcd/ziYs77QLy+4W0a0hkdcYSrn3UQMcNPP5TTvs9KMJxzYYfLpqOlm221QcQVp5qHahmpAQYcP9a78p7KnIWonneikuC6fL4d0qQ71p8=
