version: '{build}'

platform:
  - x86
  
clone_folder: C:\projects\neard

environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

install:
  - cmd: |
      git clone https://github.com/crazy-max/neard-dev.git C:\projects\temp
      move C:\projects\temp C:\projects\neard-dev
  - ps: choco install ant
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - java -version
  - ant -version

configuration:
  - Release

build_script:
  - ant release

after_build:
  - ps: |
      $env:APP_VERSION = Get-Content C:\neard-build\tmp\version.dat -Raw
      Write-Host "App version: $env:APP_VERSION"
  - cmd: move C:\neard-build\releases\%APP_VERSION% %APPVEYOR_BUILD_FOLDER%\release

artifacts:
  - path: 'release\*'
    name: release

deploy:
  tag: v$(APP_VERSION)
  release: v$(APP_VERSION)
  description: v$(APP_VERSION)
  provider: GitHub
  auth_token:
    secure: BGz5Z+cKh7a/UOFxIfBfZYho8Ghf3bO3LvaX70mdgiG1UDJhtW3FUGDjBrwyZglf
  artifact: release
  draft: true
  prerelease: false
  on:
    branch: master

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 6wcIQdnN6haB2OhAPJVhAoMpU1lLRM7tHmVUCfv2RZ/3gZSBCm7wCBde4Bx7zNyv3Qw6//VrX97ZD3ejdoyxfmFaXBomoclkVKJRcvCyn3s=
