imagick=https://github.com/Bearsampp/modules-untouched/releases/download/php-2026.6.2/php_imagick-3.8.1-8.4-ts-vs17-x64.zip
memcache=https://github.com/Bearsampp/modules-untouched/releases/download/php-2026.6.2/php_memcache-8.2-8.4-ts-vs17-x64.zip
xdebug=https://github.com/Bearsampp/modules-untouched/releases/download/php-2026.7.7/php_xdebug-3.5.3-8.4-ts-vs17-x86_64.dll
zip = https://github.com/Bearsampp/modules-untouched/releases/download/php-2026.6.2/php_zip-1.22.8-8.4-ts-vs17-x64.zip
