- name: Generate changelog
  id: changelog
  uses: metcalfc/changelog-generator@v3.0.0
  with:
    myToken: ${{ secrets.GITHUB_TOKEN }}
- name: Get the changelog
  run: |
    cat << "EOF"
    ${{ steps.changelog.outputs.changelog }}
    EOF
