name: Update Releases

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  schedule:
    - cron: '0 */8 * * *'  # Trigger every 8 hours
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-releases:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checkout the repository

    - name: Set up PHP
      uses: shivammathur/setup-php@v2  # Set up PHP
      with:
        php-version: '8.3'  # Specify PHP version 8.3

    - name: Install dependencies
      run: sudo apt-get install -y php-cli  # Install PHP CLI

    - name: Run update script
      run: php core/scripts/update-releases.php  # Run the update script

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'  # Set Git user name
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'  # Set Git user email
        git checkout -b update-releases-branch  # Create a new branch
        git add core/resources/quickpick-releases.json  # Add the updated file
        git commit -m 'Update quickpick-releases.json'  # Commit the changes

    - name: Push changes
      run: git push --set-upstream origin update-releases-branch  # Push the new branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3  # Create a pull request
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
        branch: update-releases-branch  # The branch to create the pull request from
        title: 'Update quickpick-releases.json'  # Title of the pull request
        body: 'Automated update of quickpick-releases.json'  # Body of the pull request
        base: main  # The base branch to merge into
