name: Combine JSON Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *' # Runs every 8 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  combine-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install properties

      - name: Fetch release properties files
        run: |
          node -e "
          const https = require('https');
          const fs = require('fs');
          const path = require('path');

          const urls = [
            'https://raw.githubusercontent.com/Bearsampp/module-adminer/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-apache/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-composer/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-consolez/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-filezilla/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-ghostscript/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-git/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-gitlist/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-mailhog/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-mariadb/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-memcached/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-mysql/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-ngrok/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-nodejs/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-perl/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-php/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-phpmemadmin/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-phpmyadmin/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-phppgadmin/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-postgresql/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-python/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-ruby/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-webgrind/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-xdc/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-xlight/main/releases.properties',
            'https://raw.githubusercontent.com/Bearsampp/module-yarn/main/releases.properties'
          ];

          const dir = 'releases';
          if (!fs.existsSync(dir)){
            fs.mkdirSync(dir);
          }

          urls.forEach(url => {
            const fileName = path.basename(url);
            const filePath = path.join(dir, fileName);
            const file = fs.createWriteStream(filePath);
            https.get(url, response => {
              response.pipe(file);
              file.on('finish', () => {
                file.close();
                console.log('Downloaded:', fileName);
              });
            }).on('error', err => {
              fs.unlink(filePath);
              console.error('Error downloading:', fileName, err.message);
            });
          });
          "

      - name: Combine properties into JSON
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const properties = require('properties');

          const dir = 'releases';
          const result = {};

          fs.readdirSync(dir).forEach(file => {
            const content = fs.readFileSync(path.join(dir, file), 'utf8');
            properties.parse(content, { sections: true }, (err, parsed) => {
              if (err) throw err;
              const moduleName = path.basename(file, '.properties');
              result[moduleName] = parsed;
            });
          });

          fs.writeFileSync('core/resources/quickpick-releases.json', JSON.stringify(result, null, 2));
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b updated-combined-json
          git add core/resources/quickpick-releases.json
          git commit -m 'Update combined JSON file'
          git push --force --set-upstream origin updated-combined-json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
