name: Combine releases.properties

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow
  schedule:
    - cron: '0 */8 * * *'  # Trigger every 8 hours

jobs:
  combine-json:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checkout the repository
      with:
        ref: main  # Ensure you are checking out the main branch

    - name: Install jq
      run: sudo apt-get install -y jq  # Install jq

    - name: Fetch and combine JSON files
      run: |
        urls=(
          "https://raw.githubusercontent.com/Bearsampp/module-adminer/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-apache/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-composer/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-consolez/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-filezilla/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-ghostscript/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-git/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-gitlist/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-mailhog/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-mariadb/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-memcached/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-mysql/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-ngrok/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-nodejs/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-perl/main/releases.properties"
          "https://raw.githubusercontent.com/Bearsampp/module-php/main/releases.properties"
        )
        combined_json="{}"
        for url in "${urls[@]}"; do
          json=$(curl -s "$url")
          combined_json=$(echo "$combined_json" | jq --argjson new "$json" '. * $new')
        done
        echo "$combined_json" > combined-releases.json
