name: Combine Releases Properties

on:
    schedule:
        - cron: '0 */6 * * *'  # Runs every 6 hours
    workflow_dispatch:  # Allows manual triggering

jobs:
    combine-releases:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout this repository
              uses: actions/checkout@v4
              with:
                submodules: true  # Initialize and update submodules

            - name: Checkout other repositories
              run: |
                  repos=(
                    "module-adminer"
                    "module-apache"
                    "module-composer"
                    "module-consolez"
                    "module-filezilla"
                    "module-ghostscript"
                    "module-git"
                    "module-gitlist"
                    "module-mailhog"
                    "module-mariadb"
                    "module-memcached"
                    "module-mysql"
                    "module-ngrok"
                    "module-nodejs"
                    "module-perl"
                    "module-php"
                    "module-phpmemadmin"
                    "module-phpmyadmin"
                    "module-phppgadmin"
                    "module-postgresql"
                    "module-python"
                    "module-ruby"
                    "module-webgrind"
                    "module-xdc"
                    "module-xlight"
                    "module-yarn"
                  )
                  for repo in "${repos[@]}"; do
                    echo "Cloning repository: $repo"
                    git clone "https://github.com/Bearsampp/$repo.git"
                  done

            - name: Retrieve releases.properties and combine into a single properties file
              run: |
                  combined_file="core/resources/quickpick.releases"
                  mkdir -p core/resources  # Ensure the directory exists
                  touch $combined_file
                  echo "Created combined file: $combined_file"

                  for repo in "${repos[@]}"; do
                    repo_url="https://github.com/Bearsampp/$repo"
                    echo "Processing repository: $repo"
                    if [ -f "$repo/releases.properties" ]; then
                      echo "Found releases.properties in $repo"
                      while IFS='=' read -r key value; do
                        if [ "$key" == "version" ]; then
                          version=$value
                          echo "$repo.version=$value" >> $combined_file
                          echo "$repo.url=$repo_url/releases/tag/$version" >> $combined_file
                        fi
                      done < "$repo/releases.properties"
                    else
                      echo "No releases.properties found in $repo"
                    fi
                  done

                  echo "Contents of combined file:"
                  cat $combined_file  # Debug: Display the contents of the combined file

            - name: Commit and push changes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git checkout main  # Ensure we are on the main branch
                  branch_name="update-quickpick-releases-$(date +%s)"
                  echo "branch_name=$branch_name" >> $GITHUB_ENV
                  git checkout -b $branch_name
                  git add core/resources/quickpick.releases
                  git status  # Debug: Display the git status to ensure the file is added
                  git commit -m "Update quickpick.releases"
                  git push origin $branch_name

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "Update quickpick.releases"
                  branch: ${{ env.branch_name }}
                  base: main  # Ensure the base branch is main
                  title: "Update quickpick.releases"
                  body: "This PR updates the quickpick.releases file with the latest versions from the repositories."
