name: Space to Github

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Clone JetBrains Space repository
        run: |
          git clone https://your-company.jetbrains.space/git/your-project/sandbox sandbox
        env:
          SPACE_ACCESS_TOKEN: ${{ secrets.SPACE_ACCESS_TOKEN }}

      - name: Checkout GitHub repository
        uses: actions/checkout@v2
        with:
          repository: 'Bearsampp/Bearsampp'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: '.'  # Checkout directly to the root of the workspace

      - name: Rearrange files
        run: |
          mkdir -p base
          rsync -av --exclude 'core/' sandbox/ base/
          rsync -av sandbox/core/ core/
          rm -rf sandbox

      - name: Commit changes
        run: |
          git config --global user.email "programming@hallhome.us"
          git config --global user.name "N6REJ"
          git add .
          git commit -m "Automated sync from JetBrains Space"

      - name: Push changes to GitHub
        run: |
          git push origin main

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated sync from JetBrains Space"
          pr_body: "This is an automated pull request to update from branch main of JetBrains Space"
          destination_branch: "main"

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.14.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mergeMethod: merge
