name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: .github/sync.yml
      - name: Remove File2
        uses: JesseTG/rm@v1.0.3
        with:
          path: .github/workflows/sync.yml
      - name: Remove File3
        uses: JesseTG/rm@v1.0.3
        with:
          path: .github/delete-sync.yml


